# This file generated automatically by:
#   generate_sugar_files.py
# see wiki for more info:
#   https://github.com/ruslo/sugar/wiki/Collecting-sources

if(DEFINED ICU_SOURCE_COMMON_SUGAR_CMAKE_)
  return()
else()
  set(ICU_SOURCE_COMMON_SUGAR_CMAKE_ 1)
endif()

include(sugar_files)
include(sugar_include)

sugar_include(unicode)

sugar_files(
    ICU_UC_SOURCES
    bmpset.cpp
    bmpset.h
    brkeng.cpp
    brkeng.h
    brkiter.cpp
    bytestream.cpp
    caniter.cpp
    chariter.cpp
    charstr.cpp
    charstr.h
    cmemory.c
    cmemory.h
    cpputils.h
    cstring.c
    cstring.h
    cwchar.c
    cwchar.h
    dictbe.cpp
    dictbe.h
    dtintrv.cpp
    errorcode.cpp
    filterednormalizer2.cpp
    hash.h
    icudataver.c
    icuplug.c
    icuplugimp.h
    localsvc.h
    locavailable.cpp
    locbased.cpp
    locbased.h
    locdispnames.cpp
    locid.cpp
    loclikely.cpp
    locmap.c
    locmap.h
    locresdata.cpp
    locutil.cpp
    locutil.h
    msvcres.h
    mutex.cpp
    mutex.h
    normalizer2.cpp
    normalizer2impl.cpp
    normalizer2impl.h
    normlzr.cpp
    parsepos.cpp
    propname.cpp
    propname.h
    propsvec.c
    propsvec.h
    punycode.c
    punycode.h
    putil.c
    putilimp.h
    rbbi.cpp
    rbbidata.cpp
    rbbidata.h
    rbbinode.cpp
    rbbinode.h
    rbbirb.cpp
    rbbirb.h
    rbbirpt.h
    rbbiscan.cpp
    rbbiscan.h
    rbbisetb.cpp
    rbbisetb.h
    rbbistbl.cpp
    rbbitblb.cpp
    rbbitblb.h
    resbund.cpp
    resbund_cnv.cpp
    ruleiter.cpp
    ruleiter.h
    schriter.cpp
    serv.cpp
    serv.h
    servlk.cpp
    servlkf.cpp
    servloc.h
    servls.cpp
    servnotf.cpp
    servnotf.h
    servrbf.cpp
    servslkf.cpp
    sprpimpl.h
    stringpiece.cpp
    triedict.cpp
    triedict.h
    uarrsort.c
    uarrsort.h
    uassert.h
    ubidi.c
    ubidi_props.c
    ubidi_props.h
    ubidiimp.h
    ubidiln.c
    ubidiwrt.c
    ubrk.cpp
    ubrkimpl.h
    ucase.c
    ucase.h
    ucasemap.c
    ucat.c
    uchar.c
    uchriter.cpp
    ucln.h
    ucln_cmn.c
    ucln_cmn.h
    ucln_imp.h
    ucmndata.c
    ucmndata.h
    ucnv.c
    ucnv2022.c
    ucnv_bld.c
    ucnv_bld.h
    ucnv_cb.c
    ucnv_cnv.c
    ucnv_cnv.h
    ucnv_err.c
    ucnv_ext.c
    ucnv_ext.h
    ucnv_imp.h
    ucnv_io.c
    ucnv_io.h
    ucnv_lmb.c
    ucnv_set.c
    ucnv_u16.c
    ucnv_u32.c
    ucnv_u7.c
    ucnv_u8.c
    ucnvbocu.c
    ucnvdisp.c
    ucnvhz.c
    ucnvisci.c
    ucnvlat1.c
    ucnvmbcs.c
    ucnvmbcs.h
    ucnvscsu.c
    ucnvsel.cpp
    ucol_swp.cpp
    ucol_swp.h
    udata.cpp
    udatamem.c
    udatamem.h
    udataswp.c
    udataswp.h
    uenum.c
    uenumimp.h
    uhash.c
    uhash.h
    uhash_us.cpp
    uidna.cpp
    uinit.c
    uinvchar.c
    uinvchar.h
    uiter.cpp
    ulist.c
    ulist.h
    uloc.c
    uloc_tag.c
    ulocimp.h
    umapfile.c
    umapfile.h
    umath.c
    umutex.c
    umutex.h
    unames.c
    unifilt.cpp
    unifunct.cpp
    uniset.cpp
    uniset_props.cpp
    unisetspan.cpp
    unisetspan.h
    unistr.cpp
    unistr_case.cpp
    unistr_cnv.cpp
    unistr_props.cpp
    unorm.cpp
    unorm_it.c
    unorm_it.h
    unormcmp.cpp
    unormimp.h
    uobject.cpp
    uprops.cpp
    uprops.h
    ures_cnv.c
    uresbund.c
    uresdata.c
    uresdata.h
    uresimp.h
    ureslocs.h
    usc_impl.c
    usc_impl.h
    uscript.c
    uset.cpp
    uset_imp.h
    uset_props.cpp
    usetiter.cpp
    ushape.c
    usprep.cpp
    ustack.cpp
    ustr_cnv.c
    ustr_cnv.h
    ustr_imp.h
    ustr_wcs.c
    ustrcase.c
    ustrenum.cpp
    ustrenum.h
    ustrfmt.c
    ustrfmt.h
    ustring.c
    ustrtrns.c
    utext.cpp
    utf_impl.c
    util.cpp
    util.h
    util_props.cpp
    utrace.c
    utracimp.h
    utrie.c
    utrie.h
    utrie2.cpp
    utrie2.h
    utrie2_builder.c
    utrie2_impl.h
    uts46.cpp
    utypes.c
    uvector.cpp
    uvector.h
    uvectr32.cpp
    uvectr32.h
    uvectr64.cpp
    uvectr64.h
    wintz.c
    wintz.h
)
